#!/bin/bash
set -e
if ! id bayeos > /dev/null 2>&1 
then	
	useradd bayeos
fi

service postgresql start 
chmod +x /usr/share/bayeos-server/*.sh
su - postgres -c /usr/share/bayeos-server/pg_postinst.sh

mkdir -p /var/log/bayeos
chown -R bayeos:bayeos /var/lib/bayeos-server /var/log/bayeos

chmod 700 /var/lib/bayeos-server/bayeos-server.jar
ln -sf /etc/bayeos-gateway/log4j.properties /var/lib/bayeos-server/log4j.properties

systemctl enable bayeos-server.service
service bayeos-server start  

a2enmod proxy proxy_http ssl remoteip
a2enconf bayeos-server.conf
service apache2 reload   