#!/bin/bash
set -e
if ! id bayeos > /dev/null 2>&1 
then	
	useradd bayeos
fi

systemctl start postgresql.service 

chmod +x /usr/share/bayeos-server/*.sh
su - postgres -c /usr/share/bayeos-server/pg_postinst.sh

chown -R bayeos:bayeos /var/lib/bayeos-server 

chmod 700 /var/lib/bayeos-server/bayeos-server.jar
ln -sf /etc/bayeos-gateway/logback.xml /var/lib/bayeos-server/logback.xml

systemctl enable bayeos-server.service
systemctl start bayeos-server.service  

a2enmod proxy proxy_http ssl remoteip
a2enconf bayeos-server.conf
systemctl try-reload-or-restart apache2.service    